spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_payments
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8084
