spring:
  application:
    name: user-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_users
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000ms
  
  cache:
    type: redis
    redis:
      time-to-live: 600000

server:
  port: 8081
  servlet:
    context-path: /

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 1 day
  refresh-expiration: 604800000 # 7 days

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    com.ecommerce: DEBUG
    org.springframework.security: DEBUG
